# Generated by Django 4.1.4 on 2022-12-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitat', models.CharField(max_length=40, unique=True, verbose_name='Habitat')),
            ],
            options={
                'verbose_name': 'Habitat',
                'ordering': ('habitat',),
            },
        ),
        migrations.CreateModel(
            name='SousHabitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_habitat', models.CharField(max_length=55, verbose_name='Sous-habitat')),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='habitat.habitat')),
            ],
            options={
                'verbose_name': 'Sous-habitat',
            },
        ),
    ]
