# Generated by Django 4.1.5 on 2023-04-24 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("habitat", "0002_habitat_created_at_habitat_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="soushabitat",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="soushabitat",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Sous_Habitat_Creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="soushabitat",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Date mise à jour"),
        ),
        migrations.AddField(
            model_name="soushabitat",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Sous_Habitat_Modifier",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
