# Generated by Django 4.1.5 on 2023-04-21 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geographie", "0004_municipalite_created_at_municipalite_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mrc",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Mrc_Creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mrc",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Mrc_Modifier",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
