# Generated by Django 4.2 on 2023-04-17 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habitat", "0001_initial"),
        ("geographie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteOrnitho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_du_site",
                    models.CharField(max_length=125, verbose_name="Nom du site"),
                ),
                (
                    "locid",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Id de localisation",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Longitude"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Latitude"
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, null=True, verbose_name="Site Web"),
                ),
                ("auteur", models.CharField(max_length=125, verbose_name="Auteur")),
                (
                    "miseajour",
                    models.DateField(auto_now=True, verbose_name="Mise à jour"),
                ),
                (
                    "stakeholder",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Partenaire/propriétaire",
                    ),
                ),
                (
                    "periode_interet_debut",
                    models.IntegerField(
                        choices=[
                            (0, "Toute l'année"),
                            (1, "Janvier"),
                            (2, "Février"),
                            (3, "Mars"),
                            (4, "Avril"),
                            (5, "Mai"),
                            (6, "Juin"),
                            (7, "Juillet"),
                            (8, "Août"),
                            (9, "Septembre"),
                            (10, "Octobre"),
                            (11, "Novembre"),
                            (12, "Décembre"),
                        ]
                    ),
                ),
                (
                    "periode_interet_fin",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Toute l'année"),
                            (1, "Janvier"),
                            (2, "Février"),
                            (3, "Mars"),
                            (4, "Avril"),
                            (5, "Mai"),
                            (6, "Juin"),
                            (7, "Juillet"),
                            (8, "Août"),
                            (9, "Septembre"),
                            (10, "Octobre"),
                            (11, "Novembre"),
                            (12, "Décembre"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "description_generale",
                    models.TextField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Description générale",
                    ),
                ),
                (
                    "transport",
                    models.BooleanField(
                        default=False, verbose_name="Transport en commun"
                    ),
                ),
                (
                    "acces_gratuit",
                    models.BooleanField(default=False, verbose_name="Accès gratuit"),
                ),
                (
                    "toilette",
                    models.BooleanField(default=False, verbose_name="Toilettes"),
                ),
                (
                    "picnique",
                    models.BooleanField(default=False, verbose_name="Table à picnique"),
                ),
                (
                    "banc",
                    models.BooleanField(default=False, verbose_name="Banc disponible"),
                ),
                (
                    "bon_a_savoir",
                    models.TextField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Bon à savoir",
                    ),
                ),
                (
                    "enjeux",
                    models.TextField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Enjeux de conservation",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Ébauche"), (1, "Publié")], default=1
                    ),
                ),
                (
                    "municipalite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="geographie.municipalite",
                        verbose_name="Municipalité",
                    ),
                ),
                (
                    "sous_habitat",
                    models.ManyToManyField(
                        related_name="sous_habitats",
                        to="habitat.soushabitat",
                        verbose_name="Sous habitat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteOrnithoImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125, verbose_name="Titre")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=55, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "photo_author",
                    models.CharField(max_length=125, verbose_name="Auteur"),
                ),
                ("photo_date", models.DateField(verbose_name="Date photo")),
                ("image", models.ImageField(upload_to="siteornitho/images")),
                (
                    "siteornitho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="siteornitho.siteornitho",
                    ),
                ),
            ],
        ),
    ]
