# Generated by Django 4.1.4 on 2022-12-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geographie', '0001_initial'),
        ('habitat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteOrnitho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_site', models.CharField(max_length=125, verbose_name='Nom du site')),
                ('locid', models.CharField(blank=True, max_length=8, null=True, verbose_name='Id de localisation')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Site Web')),
                ('auteur', models.CharField(max_length=125, verbose_name='Auteur')),
                ('miseajour', models.DateField(auto_now=True, verbose_name='Mise à jour')),
                ('stakeholder', models.CharField(blank=True, max_length=255, null=True, verbose_name='Partenaire/propriétaire')),
                ('periode_interet_debut', models.PositiveSmallIntegerField(choices=[(0, "Toute l'année"), (1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='Début de période')),
                ('periode_interet_fin', models.PositiveSmallIntegerField(blank=True, choices=[(0, "Toute l'année"), (1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], null=True, verbose_name='Fin de période')),
                ('description_generale', models.TextField(max_length=1024, verbose_name='Description générale')),
                ('transport', models.BooleanField(default=False, verbose_name='Transport en commun')),
                ('acces_gratuit', models.BooleanField(default=False, verbose_name='Accès gratuit')),
                ('bon_a_savoir', models.TextField(max_length=1024, verbose_name='Bon à savoir')),
                ('toilette', models.BooleanField(default=False, verbose_name='Toilettes')),
                ('picnique', models.BooleanField(default=False, verbose_name='Table à picnique')),
                ('banc', models.BooleanField(default=False, verbose_name='Banc disponible')),
                ('enjeux', models.TextField(max_length=1024, verbose_name='Enjeux de conservation')),
                ('municipalite', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='geographie.municipalite')),
                ('sous_habitat', models.ManyToManyField(to='habitat.soushabitat', verbose_name='Sous habitat')),
            ],
        ),
        migrations.CreateModel(
            name='SiteOrnithoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='Titre')),
                ('photo_author', models.CharField(max_length=125, verbose_name='Auteur')),
                ('photo_date', models.DateField(verbose_name='Date photo')),
                ('image', models.ImageField(upload_to='siteornitho/images')),
                ('siteornitho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='siteornitho.siteornitho')),
            ],
        ),
    ]
