# Generated by Django 4.1.4 on 2022-12-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitat', '0001_initial'),
        ('siteornitho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteornitho',
            name='periode_interet_debut',
            field=models.PositiveSmallIntegerField(choices=[('0', "Toute l'année"), ('1', 'Janvier'), ('2', 'Février'), ('3', 'Mars'), ('4', 'Avril'), ('5', 'Mai'), ('6', 'Juin'), ('7', 'Juillet'), ('8', 'Août'), ('9', 'Septembre'), ('10', 'Octobre'), ('11', 'Novembre'), ('12', 'Décembre')], verbose_name='Début de période'),
        ),
        migrations.AlterField(
            model_name='siteornitho',
            name='periode_interet_fin',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('0', "Toute l'année"), ('1', 'Janvier'), ('2', 'Février'), ('3', 'Mars'), ('4', 'Avril'), ('5', 'Mai'), ('6', 'Juin'), ('7', 'Juillet'), ('8', 'Août'), ('9', 'Septembre'), ('10', 'Octobre'), ('11', 'Novembre'), ('12', 'Décembre')], null=True, verbose_name='Fin de période'),
        ),
        migrations.AlterField(
            model_name='siteornitho',
            name='sous_habitat',
            field=models.ManyToManyField(related_name='sous_habitats', to='habitat.soushabitat', verbose_name='Sous habitat'),
        ),
    ]
