# Generated by Django 4.1.5 on 2023-06-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteornitho", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteornitho",
            options={"ordering": ("nom_du_site",)},
        ),
        migrations.AlterField(
            model_name="siteornitho",
            name="locid",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                unique=True,
                verbose_name="Id de localisation",
            ),
        ),
    ]
