# Generated by Django 4.1.4 on 2022-12-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteornitho', '0002_alter_siteornitho_periode_interet_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteornitho',
            name='periode_interet_debut',
            field=models.IntegerField(choices=[(0, "Toute l'année"), (1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')]),
        ),
        migrations.AlterField(
            model_name='siteornitho',
            name='periode_interet_fin',
            field=models.IntegerField(blank=True, choices=[(0, "Toute l'année"), (1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], null=True),
        ),
    ]
