# Generated by Django 4.1.5 on 2023-07-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteornitho", "0002_alter_siteornitho_options_alter_siteornitho_locid"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteornitho",
            name="raison_non_accessible",
            field=models.CharField(default="", max_length=125, verbose_name="Raison"),
        ),
        migrations.AddField(
            model_name="siteornitho",
            name="site_accessible",
            field=models.BooleanField(default=True, verbose_name="Site accessible"),
        ),
    ]
