# Generated by Django 4.1.4 on 2022-12-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteornitho', '0003_alter_siteornitho_periode_interet_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteornitho',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ébauche'), (1, 'Public')], default=1),
        ),
    ]
