# Generated by Django 4.1.4 on 2022-12-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteornitho', '0004_siteornitho_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteornitho',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ébauche'), (1, 'Publié')], default=1),
        ),
    ]
