# Generated by Django 4.1.5 on 2023-01-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteornitho", "0005_alter_siteornitho_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteornitho",
            name="enjeux",
            field=models.TextField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Enjeux de conservation",
            ),
        ),
    ]
