# Generated by Django 4.1.5 on 2023-02-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteornitho", "0006_alter_siteornitho_enjeux"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteornithoimage",
            name="description",
            field=models.CharField(
                blank=True, max_length=55, null=True, verbose_name="Description"
            ),
        ),
    ]
