# Generated by Django 4.1.5 on 2023-03-09 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geographie", "0001_initial"),
        ("siteornitho", "0007_siteornithoimage_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteornitho",
            name="bon_a_savoir",
            field=models.TextField(
                blank=True, max_length=1024, null=True, verbose_name="Bon à savoir"
            ),
        ),
        migrations.AlterField(
            model_name="siteornitho",
            name="description_generale",
            field=models.TextField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Description générale",
            ),
        ),
        migrations.AlterField(
            model_name="siteornitho",
            name="municipalite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="geographie.municipalite",
                verbose_name="Municipalité",
            ),
        ),
    ]
